# Generated by Django 3.1.4 on 2023-01-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
