# Generated by Django 3.1.4 on 2023-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planapp', '0002_auto_20230118_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
